type Query {
  """A list of all users"""
  post(id: ID!): Post
}

extend type User @key(fields: "id") {
  id: ID! @external
  posts: [Post]
}

type Post @key(fields: "id") {
  id: ID!
  date: String
  body: String
  user: User
}

