type Query {
  """A list of all users"""
  post(id: ID!): Post
  posts(userId: ID!): [Post]
}

extend type User implements Node @key(fields: "id") {
  id: ID! @external
  posts: [Post]
}

type Post implements Node @key(fields: "id") {
  id: ID!
  date: String
  body: String
  user: User
}

interface Node {
  id: ID!
}
