type Query {
  """A list of all users"""
  users: [User]
  node(id: ID!): Node
}

type User implements Node @key(fields: "id") {
  id: ID!
  username: String
}

interface Node {
  id: ID!
}

extend type Post implements Node @key(fields: "id") {
  id: ID! @external
}
